Feature/scoreboard
m1chalkubiak/devtalk-service-worker-app pull request #7
Opened 2018-11-20 15:33 UTC by appkwiatkowski

2018-11-20 21:00 UTC, m1chalkubiak requested changes

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/components/navigation/navigation.component.js
> +
unnecessary new line

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/components/navigation/navigation.component.js
> +        value={this.state.value}
This value should be determined based on the current path. Please try to use property `location` that comes to routes.

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/components/navigation/navigation.container.js
> +import { selectIsDataLoaded } from '../../modules/loader';
This select don't seems to be used

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/routes/index.js
> +
unnecessary new line

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/routes/index.js
> +                <AuthRoute exact path="/dashboard" component={Dashboard} />
Probably it will be better to leave one path that leads to dashboard, and I think that main path will fit good. So, this line can be remove. Remember to handle this change in `Navigation` component logic.

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/routes/scoreboard/scoreboard.component.js
> +import {always, equals, ifElse} from 'ramda';
Remember to check for all code styles error using lint task, before committing Your code.

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/routes/scoreboard/scoreboard.component.js
> +  sortByStatus = (users) => users.sortBy(user => user.getIn(['value', this.state.sortBy], 0)).reverse();
Currently all lists are reversed, remember about this.

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/routes/scoreboard/scoreboard.component.js
> +              <Avatar onClick={this.handleWaterConsumptionClick} alt={user.getIn(['value', 'name'])} src={user.getIn(['value', 'avatarURL'])} />
Remember to passing second argument to those function as fallback values.

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/routes/scoreboard/scoreboard.styles.js
> +import { getColor } from '../../utils/rendering';
Additional line between those imports will be advisable

2018-11-20 21:00 UTC, m1chalkubiak commented on webapp/app/routes/scoreboard/scoreboard.styles.js
> +  margin-top: 20px;
It's a little bit overly, but when we are using material ui, it would be perfect to define every spacing by multiples main unit value. Please check `getUnit` function from `rendering.js`

2018-11-22 08:19 UTC, wojciech-panek commented on webapp/app/components/navigation/navigation.container.js
> +import { selectIsDataLoaded } from '../../modules/loader';
Add elint support in IDE, this will help

2018-11-22 08:19 UTC, wojciech-panek commented on webapp/app/routes/index.js
> +import { Navigation } from "../components";
double quotes

2018-11-24 09:17 UTC, mkmieciak commented on webapp/app/components/navigation/navigation.component.js
> +            to={'#'}
You don't need curly braces around strings

2018-11-24 09:17 UTC, mkmieciak commented on webapp/app/components/navigation/navigation.component.js
> +            to={'#'}
here and above

2018-11-24 09:17 UTC, mkmieciak commented on webapp/app/routes/scoreboard/scoreboard.component.js
> +  sortByStatus = (users) => users.sortBy(user => user.getIn(['value', this.state.sortBy], 0)).reverse();
I think that better is to sort the data in selectors

2018-11-29 15:15 UTC, m1chalkubiak approved these changes

2018-11-30 08:26 UTC, wojciech-panek approved these changes

2018-11-30 08:30 UTC, merged